config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  scope "(:locale)", locale: /ru|en/ do
    get '/:locale' => 'posts#index'
    devise_for :users, controllers: { registration: "registrations" }

      get 'users/sign_out', :method => :delete
      # get '/:id/users/edit' => 'devise/registrations#edit'
      get '/users/password/edit' => 'devise/password#edit'
      get '/:id/users/edit', to: 'users#edit'
    resources :posts do
      resources :comments
    end
    resources :users do

    end
      root 'pages#about'
      get  '/:user_id/pages/index' => 'pages#index', as: 'index'

      resources :conversations, only: [:index, :show, :destroy] do
        member do
          post :reply
          post :restore
          post :mark_as_read
        end
        collection do
          delete :empty_trash
        end
      end
      resources :messages, only: [:new, :create]
        post '/messages/new', to: 'messages#new'
    resources :searches
    get '/change_locale/:locale', to: 'application#change_locale', as: :change_locale
      get 'searches', to: 'searches#search', as: :custom_search
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]

  def show
  end

  def index
    @conversations = if @box.eql? 'inbox'
                       @mailbox.inbox
                     elsif @box.eql? 'sent'
                       @mailbox.sentbox
                     else
                       @mailbox.trash
                     end

    @conversations = @mailbox.send(@box)
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  # def mark_as_read
  #   @conversation.mark_as_read(current_user)
  #   flash[:success] = 'The conversation was marked as read.'
  #   redirect_to conversations_path
  # end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def get_box
    if params[:box].blank? || !%w(inbox sent trash).include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = %w(inbox sent trash).include?(params[:box]) ? params[:box] : 'inbox'
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/_conversation.html.slim
.row
  .ui.text.container
    .ui.threaded.comments style="margin: 10px;"
      .ui.dividing.header
        h1
          = t('.subject')
          = link_to conversation.subject, conversation_path(conversation)

    .comments
      .content
        h2
          = conversation.last_message.body
        .metadata
          .date
            = conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S")
      .negative.ui.icon.button
        - if conversation.is_trashed?(current_user)
          = link_to t('.restore'), restore_conversation_path(conversation), method: :post
        - else
          = link_to t('.remove'), conversation_path(conversation), method: :delete,
                                                                        data: {confirm: t('.confirmation')}

app/views/conversations/_form.html.slim
- @recipient = User.all.collect {|p| [p.name, p.email]}
= simple_form_for :conversation, url: :conversations do |f|
  = label_tag t('.recipients'), t('.recipients')
  = select_tag t('.recipients'), recipients_options(@chosen_recipient), multiple: true, class: 'chosen-it'
  = f.input :subject, placeholder: t('.subject')
  = f.input :body, placeholder: t('.message')
  = f.button :submit, value: t('.send')

app/views/conversations/_messages.html.slim
.ui.text.container
  .row
    - @receipts.each do |receipt|
      - message = receipt.message
      h2
        = "#{t('.sender')} #{message.sender.name}"
      span
        = "#{t('.subject')} #{message.subject}"
        br
        = "#{t('.date')} #{message.created_at.strftime("%A, %b, %d, %Y at %I::%M%p")}"
        br
      = "#{t('.time')} #{message.body}"

app/views/conversations/index.html.slim
.ui.text.container
  = page_header "Your Conversations"
  .ui.inverted.segment style="margin: 10px;"
    .ui.inverted.relaxed.divided.list
      .li
        .item
          .content
            .header
              = t('.inbox')
          = mailbox_section 'inbox', @box
        .item
          .content
            .header
              = t('.sent')
          = mailbox_section 'sent', @box
        .item
          .content
            .header
              = t('.sent')
          = mailbox_section 'trash', @box
      - if @box == 'trash'
        = link_to t('.empty_trash'), empty_trash_conversations_path, method: :delete
  = render partial: 'conversations/conversation', collection: @conversations

app/views/conversations/new.html.slim
.ui.text.container
  .row
    = render partial: 'mailbox/folder_view', locals: {is_conversation: true}

app/views/conversations/show.html.slim
.ui.text.container
  .row
    = page_header "Conversation"

  h1
    = t('.subject')
    = @conversation.subject

    - @conversation.receipts_for(current_user).each do |receipt|
      - message = receipt.message
      br
      = message.sender.name
      = " t('.says_at') #{message.created_at.strftime("%-d %B %Y, %H:%M:%S") }"
      br
      = message.body
    .ui.threaded.comments
      .ui.reply.form
        .field
          = simple_form_for :message, url: reply_conversation_path(@conversation), method: :post do |f|
            = f.input :body, label: false, placeholder: t('.reply')
            = f.button :submit, value: t('.reply')