config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  scope "(:locale)", locale: /ru|en/ do
    get '/:locale' => 'posts#index'
    devise_for :users, controllers: { registration: "registrations" }

      get 'users/sign_out', :method => :delete
      # get '/:id/users/edit' => 'devise/registrations#edit'
      get '/users/password/edit' => 'devise/password#edit'
      get '/:id/users/edit', to: 'users#edit'
    resources :posts do
      resources :comments
    end
    resources :users do

    end
      root 'pages#about'
      get  '/:user_id/pages/index' => 'pages#index', as: 'index'

      resources :conversations, only: [:index, :show, :destroy] do
        member do
          post :reply
          post :restore
          post :mark_as_read
        end
        collection do
          delete :empty_trash
        end
      end
      resources :messages, only: [:new, :create]
        post '/messages/new', to: 'messages#new'
    resources :searches
    get '/change_locale/:locale', to: 'application#change_locale', as: :change_locale
      get 'searches', to: 'searches#search', as: :custom_search
  end
end

app/models/search.rb
class Search < ActiveRecord::Base
  def search_posts
    posts = Post.all

    posts = posts.where(['title LIKE ?', "%#{keywords}%"]) if keywords.present?
    posts = posts.where(['body LIKE ?', "%#{keywords}%"]) if keywords.present?
    posts = posts.where(['name LIKE ?', name]) if name.present?

    posts
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
    @search = Search.new
    @titles = Post.pluck.uniq(:title)
    @user_names = User.pluck.uniq(:name)

  end

  def create
    @search = Search.create(search_params)
    redirect_to @search
  end

  def show
    @search = Search.find(params[:id])
  end

  def search
    @articles = params[:q] ? Article.search params[:q] : []
  end

  private

  def search_params
    params.require(:search).permit(:keywords, :title, :name)
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/new.html.slim
.ui.text.container
  .row
    h1
      = t('.a_search')
    = simple_form_for @search do |f|
      = f.input :keywords, label: t('.keywords')
      = f.input :title, label: t('.title'), collection: (@titles)
      = f.input :name, label: t('.user_name'), collection: (@user_names)
      = f.button :submit, value: t('.search')
    = link_to t('.back'), :back

app/views/searches/searches.html.slim
h1
  = "Articles Search"

= simple_form_for searches_path, method: :get do |f|
  p
    = f.input :q, label: :search, collection: params[:q]
    = f.button :submit, label: "Go"

ul
  - @posts.each do |post|
    li
      h3
        = link_to article.try(:highlight).try(:title) ? article.highlight.title[0].html_safe : article.title,
          controller: "articles",
          action: "show",
          id: article._id
      - if article.try(:highlight).try(:text)
        - article.highlight.text.each do |snippet|
          p
            = snippet.html_safe

app/views/searches/show.html.slim
.ui.text.container
  .row
    h1
      = t('.result')
    = link_to t('.back'), new_search_path
    - if @search.search_posts.empty?
      = t('.no_result')
      - binding.pry
    - else
      - @search.search_posts.each do |p|
        .ui.list
          .item
            .newspaper.icon
              = link_to p.title, post_path(@post)
          .item
            .users.icon
              = p.name
      end
    end