config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  scope "(:locale)", locale: /ru|en/ do
    get '/:locale' => 'posts#index'
    devise_for :users, controllers: { registration: "registrations" }

      get 'users/sign_out', :method => :delete
      # get '/:id/users/edit' => 'devise/registrations#edit'
      get '/users/password/edit' => 'devise/password#edit'
      get '/:id/users/edit', to: 'users#edit'
    resources :posts do
      resources :comments
    end
    resources :users do

    end
      root 'pages#about'
      get  '/:user_id/pages/index' => 'pages#index', as: 'index'

      resources :conversations, only: [:index, :show, :destroy] do
        member do
          post :reply
          post :restore
          post :mark_as_read
        end
        collection do
          delete :empty_trash
        end
      end
      resources :messages, only: [:new, :create]
        post '/messages/new', to: 'messages#new'
    resources :searches
    get '/change_locale/:locale', to: 'application#change_locale', as: :change_locale
      get 'searches', to: 'searches#search', as: :custom_search
  end
end

app/models/post.rb
require 'elasticsearch/model'
class Post < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true

  has_attached_file :attached_image, styles: { medium: '600x600>', thumb: '200x200>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :attached_image, content_type: /\Aimage\/.*\Z/

  def self.search(search)
    if search
      where(['title LIKE ?', "%#{search}%"])
    else
      all
    end
  end

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :title, analyzer: 'russian', index_options: 'offsets'
      indexes :text, analyzer: 'russian'
    end
  end
end
# Post.import

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, exept: [:index, :show]
  before_action current_post
  def index
    @posts = Post.search(params[:search])
  end

  def new
    @user_name = current_user.name
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      PostMailer.post_created(user).deliver_later
      flash[:notice] = 'Post was created successfully'
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def destroy
    Post.find(params[:id]).destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :attached_image, :name, :id, :user_name)
  end

  def current_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.slim
.ui.text.container
  .a.ui.huge.green.right.ribbon.label
    = t('.new_label')
  = simple_form_for @post do |f|
    - if @post.errors.any?
      .errors
        - var = pluralize(@post.errors.count, "error")
        .h2
          = "#{pluralize(@post.errors.count, "error")} prevented this post from saving"
        .ul
          - @post.errors.full_messages.each do |msg|
            .li
              = msg
          end
    = f.input :title, label: t('.title'), required: false
    = f.input :attached_image, label: t('.image'), required: false
    = f.input :body, label: t('.post'), required: false
    = f.button :submit, value: t('.submit')

app/views/posts/edit.html.slim
.ui.text.container
  .row
    h1
      = t('.edit_post')

  = render 'form'

app/views/posts/index.html.slim
.ui.text.container
  .eight.wide.column
    .row
      - unless @posts.empty?
        .column
        .ui.piled.segment
          .ui.comments
            - @posts.each do |post|
              .ui.dividing.header
                .comment
                  .content
                    = link_to post.title, post
                  .metadata
                    .date
                      span
                        = post.created_at.strftime("%B, %d, %Y")


      .row
        .column
        - if @posts.empty?
          .row
            .a.ui.huge.green.tag.label
              = t('.label')

app/views/posts/new.html.slim
.ui.text.container
  .row
  h1
    = t('.new_post')
  = render 'form'

app/views/posts/show.html.slim
.ui.text.container
  .row
    .column
    .ui.comments.centered
      .ui.dividing.header
        .comment
          .content
            = @post.title
          .metadata
            .date
            .column
              span
                = t('.time',  time: time_ago_in_words(@post.created_at))
                - if user_signed_in?
                  = link_to t('.edit'), edit_post_path(@post)
                  = link_to t('.delete'), post_path(@post), method: :delete, data: { confirm: t('.are_you_sure') }
          .text
            .p
              - if @post.attached_image?
                = image_tag @post.attached_image(:medium)
          .text
            = @post.body
          .h2
            .text
              =  t('.comments_count', count: @post.comments.count)
              = render @post.comments
        .h3
          .text
            = t('.add_comment')
          = render "comments/form"