config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  scope "(:locale)", locale: /ru|en/ do
    get '/:locale' => 'posts#index'
    devise_for :users, controllers: { registration: "registrations" }

      get 'users/sign_out', :method => :delete
      # get '/:id/users/edit' => 'devise/registrations#edit'
      get '/users/password/edit' => 'devise/password#edit'
      get '/:id/users/edit', to: 'users#edit'
    resources :posts do
      resources :comments
    end
    resources :users do

    end
      root 'pages#about'
      get  '/:user_id/pages/index' => 'pages#index', as: 'index'

      resources :conversations, only: [:index, :show, :destroy] do
        member do
          post :reply
          post :restore
          post :mark_as_read
        end
        collection do
          delete :empty_trash
        end
      end
      resources :messages, only: [:new, :create]
        post '/messages/new', to: 'messages#new'
    resources :searches
    get '/change_locale/:locale', to: 'application#change_locale', as: :change_locale
      get 'searches', to: 'searches#search', as: :custom_search
  end
end

app/views/layouts/_flash_message.html.slim
.ui.text.container
  .row
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "ui #{name} message"

app/views/layouts/_footer.html.slim
.ui.sticky.fixed.bottom.center.aligned.fluid.container style="margin: 10px;"
  .ui.text.container
    .row.center.align
      .item style="padding: 10px; "
        i.large.users.center.aligned.icon
        = 'Created by '
        = 'Mary Sampir at 2016'
        i.copyright.icon
      .item
        i.large.mail.center.aligned.icon
        = 'Email to author'
        = 'marysaphpir@gmail.com'

app/views/layouts/_menu.html.slim
.ui.text.container
  .ui.top.secondary.pointing.stackable.menu
    .a.active.item
      = link_to t('.all_posts'), posts_path
    - if user_signed_in?
      .a.item
        = link_to t('.back'), :back
    .right.menu
      - if user_signed_in?
        .a.item
          = link_to t('.new_posts'), new_post_path
        .a.item
          = link_to t('.profile'), edit_user_registration_path(current_user)
        .a.item
          = link_to t('.all_users'), users_path
        .a.item
          = link_to t('.log_out'), destroy_user_session_path, :method => :delete

javascript:
  $('.ui.secondary.menu')
    .on('click', '.item', function() {
      if(!$(this).hasClass('dropdown')) {
        $(this)
          .addClass('active')
          .siblings('.item')
          .removeClass('active');
      }
    })

app/views/layouts/_search.html.slim
.ui.loading.search
  .ui.icon.input
    = form_tag(posts_path, :method => "get", id: "search-form") do
      = text_field_tag :search, params[:search], placeholder: t('.search')
    i.search.icon
  .results

app/views/layouts/_sidebar.html.slim
.ui.text.container
  .ui.visible.left.vertical.menu.sidebar
    h1
      = t('.website')
    - if user_signed_in?
      .a.active.item
        = link_to t('.blog'), index_path(current_user)
      .a.item
        = link_to "Inbox", conversations_path
    .a.item
      = link_to t('.about'), root_path

    = render 'layouts/search'

    h1
      = t('.social')
    .a.item
      .ui.green.basic.button
        = link_to t('.start'), new_message_path
    / .a.item
      / = link_to "custom search", custom_search_path
    .a.item
      - if I18n.locale == :ru
        = link_to "en", change_locale_path(:en)
      - else
        = link_to "ru", change_locale_path(:ru)
    .a.item
      = t('.vk')
    .a.item
      = t('.tweeter')
  .a.item
javascript:
  $('.ui.left.menu')
    .on('click', '.item', function() {
      if(!$(this).hasClass('dropdown')) {
        $(this)
          .addClass('active')
          .siblings('.item')
          .removeClass('active');
      }
    })

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = 'MainBlog'
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

body
  = render 'layouts/menu'
  = render 'layouts/flash_message'
  = render 'layouts/sidebar'
  - flash.each do |key, value|
    ."#{flash_class(key)}"
      = value
  end
  = yield
  = render 'layouts/footer'